### ISSUE TITLE
Data - Collect Student Info: Collect student info & create JSON file

### ISSUE THREAD

**Issue by heosman** [SeattleColleges/SeattleColleges.github.io#10]
**Tasks**
Collect the following from each student:
- [x] Photo that represents student
- [x] Role taken in practicum
- [ ] About me blurb
- [x] Email
- [x] Github link
- [ ] Linkedin link

Other tasks:
- [x] Create a JSON file with this info
- [x] Add student images to images folder
