### ISSUE TITLE
USER STORY: Data - Collect Student Info

### ISSUE THREAD

**Issue by heosman** [SeattleColleges/SeattleColleges.github.io#9]
**Tasks**
Collect the following from each student:
- [x] Photo that represents student
- [x] Role taken in practicum
- [x] About me blurb
- [x] Email
- [x] Github link
- [x] Linkedin link

Other tasks:
- [x] Create a JSON file with this info
- [x] Add student images to images folder

**Comment by nickolasram** [comment]
@heosman Can you commit what you have so far, with null values for any missing fields, and create a pull request? You can continue to work on this after. It would just be helpful to have some data to work with while styling.

**Comment by heosman** [comment]
@nickolasram I already merged [the PR](https://github.com/SeattleColleges/SeattleColleges.github.io/pull/11) for this. There hasn't been any new info to add since then.

**Comment by nickolasram** [comment]
Okay, perfect. I see it now 👍
